In [1]:

import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB

import warnings
warnings.filterwarnings("ignore")                     #Ignoring unnecessory warnings

import numpy as np                                  #for large and multi-dimensional arrays
import pandas as pd                                 #for data manipulation and analysis
import nltk                                         #Natural language processing tool-kit

from nltk.corpus import stopwords                   #Stopwords corpus
from nltk.stem import PorterStemmer                 # Stemmer

from sklearn.feature_extraction.text import CountVectorizer          #For Bag of words
from sklearn.feature_extraction.text import TfidfVectorizer          #For TF-IDF
from gensim.models import Word2Vec                                   #For Word2Vec

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense



D:\Users\USER\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
D:\Users\USER\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
D:\Users\USER\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


In [8]:
!python -V

Python 3.7.10


In [9]:
import os
import pandas as pd

df = pd.read_csv("/content/training_set_rel3.tsv", sep='\t', encoding='ISO-8859-1',engine="python", quotechar='"', error_bad_lines=False)
df = df.dropna(axis=1)
df = df.drop(columns=['rater1_domain1', 'rater2_domain1'])
df = df.drop(columns=['essay_id', 'essay_set'])
df.head()

Skipping line 9: '	' expected after '"'
Skipping line 139: '	' expected after '"'
Skipping line 225: '	' expected after '"'
Skipping line 379: '	' expected after '"'
Skipping line 542: '	' expected after '"'
Skipping line 603: '	' expected after '"'
Skipping line 650: '	' expected after '"'
Skipping line 668: '	' expected after '"'
Skipping line 841: '	' expected after '"'
Skipping line 846: '	' expected after '"'
Skipping line 850: '	' expected after '"'
Skipping line 867: '	' expected after '"'
Skipping line 909: '	' expected after '"'
Skipping line 911: '	' expected after '"'
Skipping line 940: '	' expected after '"'
Skipping line 988: '	' expected after '"'
Skipping line 1065: '	' expected after '"'
Skipping line 1068: '	' expected after '"'
Skipping line 1117: '	' expected after '"'
Skipping line 1169: '	' expected after '"'
Skipping line 1392: '	' expected after '"'
Skipping line 1668: '	' expected after '"'
Skipping line 1724: '	' expected after '"'
Skipping line 6975: '	' expec

essay  domain1_score
0  Dear local newspaper, I think effects computer...              8
1  Dear @CAPS1 @CAPS2, I believe that using compu...              9
2  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...              7
3  Dear Local Newspaper, @CAPS1 I have found that...             10
4  Dear @LOCATION1, I know having computers has a...              8

In [10]:
list_1 = []
list_2 = []
list_3 = []
list_4 = []
list_5 = []
list_6 = []
list_7 = []
list_8 = []
list_9 = []
list_10 = []

In [11]:
data = []
num = [1,2,3,4,5,6,7,8,9,10]
count = 0
for i,j in zip(range(len(df)),df["essay"]):
    if df["domain1_score"][i] == 1:
        list_1.append(j)
    if df["domain1_score"][i] == 2:
        list_2.append(j)
    if df["domain1_score"][i] == 3:
        list_3.append(j)
    if df["domain1_score"][i] == 4:
        list_4.append(j)
    if df["domain1_score"][i] == 5:
        list_5.append(j)
    if df["domain1_score"][i] == 6:
        list_6.append(j)
    if df["domain1_score"][i] == 7:
        list_7.append(j)
    if df["domain1_score"][i] == 8:
        list_8.append(j)
    if df["domain1_score"][i] == 9:
        list_9.append(j)
    if df["domain1_score"][i] == 10:
        list_10.append(j)
   

In [12]:
import itertools
data = list(itertools.chain(list_1,list_2,list_3,list_4,list_5,list_6,list_7,list_8,list_9,list_10))
len(data)

10294

In [13]:
def gen_num(num,length):
    num_list = [num]*length
    return num_list

In [14]:
score_1 = gen_num(1,len(list_1))
score_2 = gen_num(2,len(list_2))
score_3 = gen_num(3,len(list_3))
score_4 = gen_num(4,len(list_4))
score_5 = gen_num(5,len(list_5))
score_6 = gen_num(6,len(list_6))
score_7 = gen_num(7,len(list_7))
score_8 = gen_num(8,len(list_8))
score_9 = gen_num(9,len(list_9))
score_10 = gen_num(10,len(list_10))

score = list(itertools.chain(score_1,score_2,score_3,score_4,score_5,score_6,score_7,score_8,score_9,score_10))
len(score)


10294

In [15]:
# dictionary of lists 
dictnary = {'essay': data, 'score': score}     
df = pd.DataFrame(dictnary) 
df 

essay  score
0      Write a persuasive essay to a newspaper reflec...      1
1      If the people that are publishing and writing ...      1
2      I do think that there should be a censorship i...      1
3      I belive that they need to keep every thing an...      1
4      Hi my name is @CAPS1 @CAPS2 @PERSON1 and I'm h...      1
...                                                  ...    ...
10289  A time I was patient was when I had to be pati...     10
10290  Being patient is hard to be. First of all its ...     10
10291  One day I was watching @CAPS1. I was bored the...     10
10292  My own way about patient is that when somebody...     10
10293                              I dont like computers     10

[10294 rows x 2 columns]

In [16]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [17]:
stop_words = set(stopwords.words('english'))
len(stop_words) #finding stop words

179

In [18]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
snow = nltk.stem.SnowballStemmer('english')

corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['essay'][i])
    review = review.lower()
    review = review.split()
    
    review = [snow.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [20]:
voc_size=5000
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
type(onehot_repr)

list

In [21]:
sent_length=400
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1874 1033 2625]
 [   0    0    0 ... 2634  190  190]
 [   0    0    0 ...  893 4740 2246]
 ...
 [   0    0    0 ... 1470 2246 4275]
 [   0    0    0 ...  567 3397  922]
 [   0    0    0 ...  434 1191 4275]]


In [3]:
## Creating model
embedding_vector_features=400
voc_size=5000
sent_length=400
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(10,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 400, 400)          2000000   
_________________________________________________________________
dropout (Dropout)            (None, 400, 400)          0         
_________________________________________________________________
lstm (LSTM)                  (None, 100)               200400    
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense (Dense)                (None, 10)                1010      
Total params: 2,201,410
Trainable params: 2,201,410
Non-trainable params: 0
_________________________________________________________________
None


In [4]:
model.load_weights("./models/final_lstm-0.56.h5")

In [23]:
df_x = df['essay']
df_y = df['score']

Y = pd.get_dummies(df['score']).values

In [24]:

X_final=np.array(embedded_docs)
y_final=np.array(df_y)

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_final, Y, test_size=0.2, random_state=42)

In [26]:
#we are feeding the 
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=100,batch_size=64)

Epoch 1/100
129/129 [==============================] - 42s 69ms/step - loss: 0.4076 - accuracy: 0.2212 - val_loss: 0.2445 - val_accuracy: 0.3327
Epoch 2/100
129/129 [==============================] - 8s 65ms/step - loss: 0.2334 - accuracy: 0.4119 - val_loss: 0.1839 - val_accuracy: 0.5454
Epoch 3/100
129/129 [==============================] - 8s 64ms/step - loss: 0.1832 - accuracy: 0.5755 - val_loss: 0.1707 - val_accuracy: 0.6013
Epoch 4/100
129/129 [==============================] - 8s 63ms/step - loss: 0.1651 - accuracy: 0.6327 - val_loss: 0.1596 - val_accuracy: 0.6285
Epoch 5/100
129/129 [==============================] - 8s 64ms/step - loss: 0.1456 - accuracy: 0.6892 - val_loss: 0.1613 - val_accuracy: 0.6289
Epoch 6/100
129/129 [==============================] - 8s 65ms/step - loss: 0.1320 - accuracy: 0.7247 - val_loss: 0.1648 - val_accuracy: 0.6246
Epoch 7/100
129/129 [==============================] - 8s 63ms/step - loss: 0.1193 - accuracy: 0.7632 - val_loss: 0.1739 - val_accuracy

In [28]:
model.save('final_lstm-0.56.h5')

In [51]:
y_pred_lstm = model.predict_classes(X_test)

In [58]:
list_num = []
for i in range(Y_test.shape[0]):
  num = np.sum(Y_test[i])
  list_num.append(num)

In [60]:
preds = pd.get_dummies(y_pred_lstm).values

In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,preds)

0.565808644973288

In [62]:
cohen_kappa_score(Y_test,preds)

ValueError: ignored

# ML

In [28]:
final_tf = df_x
tf_idf = TfidfVectorizer(ngram_range=(1,2),max_features=5000)
tf_data = tf_idf.fit_transform(final_tf)
print(tf_data[1])

  (0, 2809)	0.10759649051024821
  (0, 4038)	0.10987202686433616
  (0, 2895)	0.03946479713199625
  (0, 3986)	0.10675876521893803
  (0, 1521)	0.05534587620638789
  (0, 3296)	0.07668314023921995
  (0, 4184)	0.06821170079153574
  (0, 4151)	0.0536595337112696
  (0, 1920)	0.06210826252600375
  (0, 4213)	0.06844612211843353
  (0, 4048)	0.0806187506434992
  (0, 2332)	0.07043587677495616
  (0, 1147)	0.0923651653920665
  (0, 2949)	0.09671389181091368
  (0, 586)	0.08192251637371306
  (0, 2029)	0.10635361339817855
  (0, 3399)	0.10175933056284568
  (0, 250)	0.09056315884993957
  (0, 3845)	0.10675876521893803
  (0, 2331)	0.0785247263044646
  (0, 2190)	0.08601367471348947
  (0, 4361)	0.05418859826654228
  (0, 4685)	0.061959617672071886
  (0, 717)	0.08770264108222585
  (0, 4272)	0.10207520676492184
  :	:
  (0, 4148)	0.11653903739325364
  (0, 4108)	0.08566986574191424
  (0, 369)	0.10675876521893803
  (0, 4139)	0.1841602575621102
  (0, 4919)	0.07825657419956007
  (0, 314)	0.13248960164958362
  (0, 3057)

In [31]:
tf_data.shape

(10294, 5000)

In [32]:
SEED =42
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val = train_test_split(tf_data,df_y,test_size = 0.2,random_state=SEED)

In [34]:
y_train.shape

(8235,)

In [46]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf_model = rf.fit(x_train,y_train)
y_pred_rf = rf_model.predict(x_val)
accuracy_score(y_val,y_pred_rf)

0.5716367168528412

In [2]:
import sklearn as sk
print(sk.__version__)

0.22.2.post1


In [47]:
from sklearn.metrics import cohen_kappa_score
cohen_kappa_score(y_val,y_pred_rf)

0.4618145243025962

In [37]:
import pickle
pickle.dump(rf_model, open("model_rf-0.5726.pkl", "wb"))

In [45]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]



random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

cls_rf_rscv = RandomForestClassifier()
from sklearn.model_selection import RandomizedSearchCV

random_search_rf = RandomizedSearchCV(cls_rf_rscv, random_grid,n_iter=5, n_jobs=1, cv=5,verbose=2)
random_search_rf.fit(x_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] n_estimators=200, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=20, bootstrap=True 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  n_estimators=200, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=20, bootstrap=True, total=  15.6s
[CV] n_estimators=200, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=20, bootstrap=True 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   15.6s remaining:    0.0s


[CV]  n_estimators=200, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=20, bootstrap=True, total=  15.5s
[CV] n_estimators=200, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=20, bootstrap=True 
[CV]  n_estimators=200, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=20, bootstrap=True, total=  15.6s
[CV] n_estimators=200, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=20, bootstrap=True 
[CV]  n_estimators=200, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=20, bootstrap=True, total=  15.5s
[CV] n_estimators=200, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=20, bootstrap=True 
[CV]  n_estimators=200, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=20, bootstrap=True, total=  15.4s
[CV] n_estimators=200, min_samples_split=5, min_samples_leaf=2, max_features=sqrt, max_depth=60, bootstrap=False 
[CV]  n_estimators=200, min_samples

[Parallel(n_jobs=1)]: Done  25 out of  25 | elapsed: 50.9min finished


RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [46]:
random_search_rf.best_params_

{'bootstrap': False,
 'max_depth': 40,
 'max_features': 'sqrt',
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'n_estimators': 2000}

In [38]:
SEED=42
base_model = RandomForestClassifier(bootstrap= False,
                                    max_depth= 40,
                                    max_features= 'sqrt',
                                    min_samples_leaf= 2,
                                    min_samples_split= 2,
                                    n_estimators= 2000,
                                    random_state = SEED)
base_model.fit(x_train, y_train)

RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=40, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=2000,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [39]:
y_pred_rf_rscv = base_model.predict(x_val)

In [40]:
# y_pred_rf_rscv = rf_rscv_model.predict(x_val)
accuracy_score(y_val,y_pred_rf_rscv)

0.597377367654201

In [45]:
import pickle
pickle.dump(rf_model, open("model_rf_rscv-0.59727.pkl", "wb"))

In [44]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import (AdaBoostClassifier,GradientBoostingClassifier,ExtraTreesClassifier)
from sklearn.tree import DecisionTreeClassifier
SEED=42
base_learners = [
                 ('rf', RandomForestClassifier(bootstrap= False,max_depth= 40,max_features= 'sqrt',min_samples_leaf= 2,min_samples_split= 2,n_estimators= 2000,random_state = SEED)),
                 ('adb',AdaBoostClassifier(n_estimators=100, random_state=SEED)),
                 ('ext',ExtraTreesClassifier(n_estimators=100, random_state=SEED)),
                 ('gbc',GradientBoostingClassifier(n_estimators=100,random_state=SEED)),
                 ('svc', SVC())
    
    
                ]

# Initialize Stacking Classifier with the Meta Learner
stk_clf = StackingClassifier(estimators=base_learners, final_estimator=LogisticRegression())

stk_clf.fit(x_train, y_train)

KeyboardInterrupt: ignored